name: Ejecutar Script Bash Manualmente

on:
  workflow_dispatch:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ejecutar script Bash
        run: |
          # Aquí puedes agregar tus comandos Bash
          echo "Ejecutando script Bash"
          ./mi-script-bash.sh
